# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               穿裤子的云
tagline:             'nieyong的画家梦想'
description:         '这里收集了nieyong的文艺梦想，主要是诗歌/科幻/绘画。'
url:                 
baseurl:             /
paginate:            5

# About/contact
author:
  name:              nieyong
  url:               
  email:             nieyong2010@gmail.com

# Custom vars
version:             1.0.0
